# Generated by Django 3.1.7 on 2021-03-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[('stock', 'stock'), ('done', 'done')], default='stock', max_length=10)),
            ],
        ),
    ]
